### ISSUE TITLE
Bug - You can place Infinite Water bucket in a World Guard Region

### ISSUE THREAD

**Issue by NyhmsQuest** [oddlama/vane#102]
Players can bypass a worldguard region and place water with infinite water bucket when they shouldn't be able to.

**Comment by oddlama** [comment]
Are you actually talking about a world-guard region? In that case I don't see how vane can be involved.

**Comment by NyhmsQuest** [comment]
Normal water buckets can't be placed inside the region but the infinite water buckets can, it's as if they just ignore the fact that there is a world guard region

**Comment by ryantheleach** [comment]
@NyhmsQuest Forgive me for being ignorant, if it's a vane feature I'm not using, but what is an "infinite water bucket"?

**Comment by NyhmsQuest** [comment]
> @NyhmsQuest Forgive me for being ignorant, if it's a vane feature I'm not using, but what is an "infinite water bucket"?

No forgive me for being an absolute idiot and reporting a bug to the wrong plugin, the infinite water bucket isn't part of Vane.
Many apologize, I feel like such an idiot right now

**Comment by oddlama** [comment]
No worries
