### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by broliant112** [oddlama/vane#103]
I use Minehut for hosting, and I'm using Paper 1.18.1. I have the jar files in the plugins folder, but it doesn't consider them as plugins. I also have ProtocolLib and it still won't pick up Vane as an actual plugin.

**Comment by oddlama** [comment]
Sorry that's not an issue we can help you with. Please contact your hosting provider regarding such issues. vane is a regular plugin and requires no extra care to be installed.
