### ISSUE TITLE
Localising the website

### ISSUE THREAD

**Issue by karthanistyr** [oddlama/vane#104]
It's recently been made obvious to me that although the mod itself is fully localised, the documentation (website) was not.
Any opinions on how to do that ?

**Comment by karthanistyr** [comment]
The simplest approach would be to duplicate index.html into index.<lang>.html and translating there, adding links to the various locales at the top (deaulting to english). Drawback is that the page structure is duplicated and any change would have to be mirrored manually.

More complete, more robust approach would propbably be something like https://letrastudio.github.io/jekyll-i18n/

**Comment by oddlama** [comment]
The website itself is available in the `docs/` folder. The only relevant part for localization is the `index.html` - it's just a static and very simple website.

Ideally, I would split all translatable strings from the index.html into subfiles for each language and assemble them into separate files with a language selector whenever the page is rebuilt. Going forward, I'm tempted using [gitbook](https://gitbook.com) in the future, where we could translate pages individually. But this would make the whole documentation less accessible and seemingly more complex with all the subpages.

**Comment by karthanistyr** [comment]
> Ideally, I would split all translatable strings from the index.html into subfiles for each language and assemble them into separate files with a language selector whenever the page is rebuilt. 

Yes that would probably be a nice stop gap, shy of implementing a full i18n solution (which doesn't look straightforward with Jekyll and therefore a much higher bar to meet). Would be happy to provide the French version if you come around to doing that.

**Comment by ryantheleach** [comment]
I'm not sure how to tie it in, but Sponge previously used readthedocs with https://crowdin.com/

**Comment by oddlama** [comment]
I currently don't have the time to do this properly. If I ever get to write a new translation system (https://github.com/oddlama/vane/issues/118) I will include this.
