### ISSUE TITLE
use server side translation for message styling by players to not break plugins like discordsrv

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#108]
it doesn't add a lot of value to do this one client side, as there is no localization in that specific string.

**Comment by ryantheleach** [comment]
The only thing I can think of, is potential RTL languages?

**Comment by oddlama** [comment]
Uh maybe, but that shouldn't be too concerning as the only style we are adding is color, so if the text is RTL everything would still work (except from names being on the left i guess, but thats the default anyways). Not that there'd be any translations for RTL languages.

**Comment by oddlama** [comment]
Done
