### ISSUE TITLE
Spaces in Server Foldername = ERROR

### ISSUE THREAD

**Issue by Hypano** [oddlama/vane#11]
As in Title. 
I always got Error Messages "NoSuchFileException".

as the Folder was names "Minecraft Paper Server"

But as soon as i renamed it to "Minecraft_Paper_Server" 
Everything worked fine

**Comment by oddlama** [comment]
Thanks for the report. Can you post the full error message you got so that I can investigate where the problem occurs specifically?

**Comment by oddlama** [comment]
Nevermind I just had a lucky guess and it's fixed. Will upload new version soon.
