### ISSUE TITLE
True North Compass

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#115]
> Lindse — Today at 4:22 AM
> dunno if it would be possible, but a tiny addition to trifles: Perhaps a north star of sorts, a star that doesn't move and can be used for navigation so you don't have to open the f3 menu to see your direction if its night
> or an alternate compass (maybe made out of copper?) that always points north/south

This seems like a pretty easy instant-add.

Just need to investigate recipe + texture.

The copper recipe seems apt, but I fear that Mojang may want it for themselves.

**Comment by oddlama** [comment]
We can use it until they do. And if they do we can change the recipe easily.
