### ISSUE TITLE
Time Command not working on Commandblock

### ISSUE THREAD

**Issue by Hypano** [oddlama/vane#12]
Do i miss something (pretty new to all of that and trying and reading alot), but i wasnt able to find any realted to that in any of those config files.

I have alot of button and redstone powered Commandblocks, but they dont to "Time set day" anymore. and the new "Time day world" wont work too, it only works if i put it in the chat myself.

**Comment by oddlama** [comment]
Vane implements it's own `/time` command that changes the time smoothly instead of instantly. Probably your command blocks are now referring to vanes implementation. If you want to use the minecraft's `/time` command, i think you can use `/minecraft:time` instead.

**Comment by Hypano** [comment]
I really prefer the smooth change, instead of the vanilla instantly change.
But Still this Workaround works and i will change all commands tho that.

Thx alot!

**Comment by oddlama** [comment]
Sure! If you prefer the smooth version, you may still use vane's command, but it has a slightly different syntax (try `/time help` for a listing).

**Comment by Hypano** [comment]
Vanes syntax "/time day world" only works by typing it into chat myself, the commandblock wont execute this, atleast at my end, and the Console does not write anything, when trying to use the CB for it.  
Other Commands get executed, like the Workaround you told me. 

Maybe the CB doesnt have the Permissions for it ? It seems, like they cant execute any of vanes commands, even writen as "vane:..."
Do i miss something or maybe just doing it completly wrong?

**Comment by oddlama** [comment]
When you explicitly specify the world, it should need to be executed by a player. Nonetheless, I have never tested vane commands in command blocks, so it might indeed be broken :/ I'll add it to my todo list to investigate when I have some time :)

**Comment by Hypano** [comment]
"When you explicitly specify the world, it shouldn't need to be executed by a player" Yup you are right, console works then. 
But CB still doesnt.

That would be real cool, this timeskip looks awesome :)
Have a nice day! Ill try if i can workaround with sudo of essentials, but not installed yet.
