### ISSUE TITLE
new item: trowel

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#120]
Idea from [tweakin](https://www.spigotmc.org/resources/tweakin-1-17-1-18.93444/).

Places a random block from your hotbar. Useful to create paths and walls with block variety and fits nicely into vane.
Probably only iron variant.

**Comment by ryantheleach** [comment]
I'm all for this.

How would it work functionally? right click air to bring up a menu that is a mirror of your hotbar, allowing you to exclude slots?

**Comment by oddlama** [comment]
I imagined it even simpler than that, by just using any block that is in your hotbar. To exclude some you can just naturally move them to your inventory and we don't even need to bother with a menu.

**Comment by synuhaan** [comment]
Another idea, some way to use a random item from a bundle. If you have an bundle in your off-hand
