### ISSUE TITLE
Right click shulkerbox to open.

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#126]
We had this in an earlier version of vane, and I want it back. (Back then it was a craftable enchantment, but I think this should always work).

Another thought: When you are in your inventory and click with an itemstack on the cursor on a shulkerbox, it could place the stack in the shulkerbox without needing to open it.

**Comment by oddlama** [comment]
Ah opening shulkerboxes could also be allowed from an opened inventory by right-clicking it.

**Comment by FordFriedel** [comment]
With shulker boxes becoming more accessible with this feature, would we consider allowing shulkers to receive the soulbound enchantment?

**Comment by oddlama** [comment]
Closed by implementing backpacks (#129)
