### ISSUE TITLE
bedtime messages are spamming the chat

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#127]
We could make those into action-bar messages that get displayed for players in the relevant world. Thoughts?

**Comment by ryantheleach** [comment]
Actionbar is what I would recommend, only problem is that vanilla also uses the action bar for bed related stuff.

Care is needed in testing to make sure that it doesn't obliterate the vanilla messages, without adding to it.

**Comment by oddlama** [comment]
I can currently only remember "bed too far away", "monsters nearby" and "too far away" messages. are there any messages while sleeping?

**Comment by ryantheleach** [comment]
1.17 introduces gamerules surrounding % based player sleep voting.

These messages are communicated via the action bars.

**Comment by oddlama** [comment]
Ahh true! That almost makes the plugin obsolete haha

**Comment by oddlama** [comment]
Do you know if it displays`current sleepers/required sleepers` or `current sleepers/players in world`? Haven't got enough people at hand to test it myself.

**Comment by oddlama** [comment]
I'd probably just send an action message when a player enters the bed, overriding the vanilla message.
It would be broadcast to the action bar of all players in the relevant world and display:

`<player> is sleeping <n_sleeping>/<n_required>`

@ryantheleach Any objections?
