### ISSUE TITLE
automatic item search in nearby chests.

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#128]
I'm dumb and I need this. Currently I'm panic-opening all my chests to find where I have the rest of my logs. I've first seen a feature like this added by Botania back in FTB Infinity.

Basically the idea is that you open your inventory, middle-click an item (or maybe shift-rightclick when there is no connected inventory), then vane will search for the item in nearby chests in the adjacent chunks around the player and visualize that. This can even be performant because we can get a list of all tileentities in a chunk without iterating blocks. Then a particle trail will be spawned to show all chests that contain an item of the same material. If there were see-through-walls particles I'd use them for that.

**Comment by ryantheleach** [comment]
debug block highlights maybe?

**Comment by oddlama** [comment]
definitely a valid option. Although I'm not sure whether I like the aesthetics
