### ISSUE TITLE
Convenience recipes?

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#130]
I've seen that quark adds some nice convenience recipes.
Ideally I'd like to add some more cutting recipes to the stonecutter for wood,
as mojang never thought we need a woodcutter. Also maybe a way to recombine slabs to solid blocks.

Some recipe ideas from quark:

![image](https://user-images.githubusercontent.com/31919558/152461954-beb48071-1403-4abb-be0b-d86be402b75d.png)
![image](https://user-images.githubusercontent.com/31919558/152461847-1df308f2-3bf0-4f7b-83c8-e62ecca158af.png)
![image](https://user-images.githubusercontent.com/31919558/152461781-d97dca13-308a-4955-9b2d-a5c4e11aa3d4.png)
![image](https://user-images.githubusercontent.com/31919558/152461816-0e527631-e033-4149-ab74-4f3e01759528.png)

**Comment by ryantheleach** [comment]
Plain and simple recipes like this I think are best supplied by datapacks that already exist, even PaperTweaks recommend datapacks for simple recipe changes.

If there was something further or dynamic vane could add, it would make sense for inclusion.

Possibly just a link to a recommended datapack?

**Comment by oddlama** [comment]
Ah right, these things exist now :D Yes probably a link to a recommended datapack then.
