### ISSUE TITLE
Investigate using xaero's minimap waypoints

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#138]
It would be really nice if vane also supported xaero's minimap waypoints in addition to bluemap/dynmap/squremap

https://www.spigotmc.org/resources/minimapapi.35354/

Not sure if that library is published or safe, need to do some investigation.

Could also potentially tie into portal discover feature we discussed, since these waypoints are trivial to implement per player.

**Comment by MagnusHJensen** [comment]
To add on to this, to speak on the validity of the plugin.
Even though it's old and released back in 2017 it was co-authored by xaero96, which is the creator of xaero's mm and wm, so It's safe to use, but it would be nice to just add the code instead of having to rely on a third party lib for something that small.

**Comment by oddlama** [comment]
I'm not at all opposed to adding this! Sounds like a perfectly reasonable addition! Usually, I just add the features I need for my own needs, which is why this has been kind of stale. So I'd be super happy if anyone would create a PR for this! :D

**Comment by Serial-ATA** [comment]
I tried this out, and the plugin tries to register an invalid channel name. Looks like the requirements changed in 1.13. Given the plugin and mod are closed source, I don't think this is possible.

**Comment by oddlama** [comment]
Ah that's too bad, I guess I'll close this then. Thanks for checking.

**Comment by Serial-ATA** [comment]
Spoke to xaero96 about this, and they plan on making a new API for this in the future. Don't know when as of now.
