### ISSUE TITLE
1.19 Support

### ISSUE THREAD

**Issue by thatmirc** [oddlama/vane#148]
I know its early in the update but I thought I'd just make this issue so we can track when its updated.

Update to 1.19

**Comment by oddlama** [comment]
Already in progress. Currently we need to wait for PaperMC to release at least one experimental build.

**Comment by oddlama** [comment]
update: I've finished converting all code to 1.19, but cannot start testing until a runnable server version is released by papermc :)

**Comment by oddlama** [comment]
Great news: Everything seems to work without further changes :)
