### ISSUE TITLE
Translation: French

### ISSUE THREAD

**Issue by karthanistyr** [oddlama/vane#15]
Hi, I'm toying with the idea to translate this mod to French. What will it take to fully translate all strings to French? Looking for pointers.

Disclosure: I'm a native French speaker and fluent in English.

**Comment by oddlama** [comment]
Your efforts would be highly appreciated! I'm glad to hear that you'd like to translate the plugin.

For reference: To create a full translation, you will need to create the `lang-fr.yml` file for all vane modules. For the german one it took me about a day to translate every module. There are currently about 200 distinct strings or messages that need translation, and the rest is either trivial or repetitive.

The gist is, that for each resource folder `vane-<something>/src/main/resources/` in the project, except for vane-waterfall, you need to do the following:
1. Copy `lang-en.yml` to `lang-fr.yml`
2. Replace the country code `en_us` at the top with `fr_fr`
3. Translate all messages

There are some details that are important to know beforehand. I've written a wiki page on [Creating a Translation](https://github.com/oddlama/vane/wiki/Creating-a-Translation) to guide you and future contributors through the process. If anything is unclear, don't hesitate to ask!

**Comment by karthanistyr** [comment]
Tanks for this

I might actually need a little help wrt compiling the project though... On a fresh clone, 
```
karthanis@karth-arch ~/Documents/minecraft/vane (git)-[master] % ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-7.0-bin.zip
..........10%...........20%...........30%..........40%...........50%...........60%...........70%..........80%...........90%...........100%

Welcome to Gradle 7.0!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/karthanis/Documents/minecraft/vane/build.gradle' line: 43

* What went wrong:
A problem occurred evaluating root project 'vane'.
> Could not get unknown property 'signJar' for project ':vane-admin' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s
./gradlew build  8,36s user 2,88s system 14% cpu 1:18,53 total
```
It does look like there's a missing `signJar` task somewhere in the build files, any help appreciated.

**Comment by oddlama** [comment]
Ah thanks for pointing that out. I sign all official releases cryptographically and forgot to properly skip the signing step when no signing key is given. I've just quickly pushed a fix, so you if you rebase your branch on origin/master everything should compile.

**Comment by karthanistyr** [comment]
Thanks for the quick reply, I got a little bit further, still a small hurdle though
```
karthanis@karth-arch ~/Documents/minecraft/vane (git)-[master] % ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':vane-core:shadowJar'.
> Could not resolve all dependencies for configuration ':vane-core:runtimeClasspath'.
   > Could not find :patched_1.16.5:.
     Searched in the following locations:
       - file:/home/karthanis/Documents/minecraft/vane/libs/patched_1.16.5.jar
     Required by:
         project :vane-core
         project :vane-core > project :vane-annotations

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
```
Almost there :p

**Comment by oddlama** [comment]
Ah that's easy, you are missing the first step described in [Building from Source](https://github.com/oddlama/vane/blob/master/README.md#building-from-source) :)

**Comment by karthanistyr** [comment]
Ah yes, [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC). I can start working on the actual translation now. Thanks for your support.

**Comment by oddlama** [comment]
No worries - I'm looking forward to it!
