### ISSUE TITLE
Can I use the 1.19 plugin version with 1.18.2 ?

### ISSUE THREAD

**Issue by cfouche3005** [oddlama/vane#150]
Basicaly the title, paper 1.19 is experimental and my console is spammed by vane who want me to update.

**Comment by oddlama** [comment]
Unfortunately we don't support several major versions at once, as we depend on the mojang api for a lot of features. So only 1.19 can be supported with the newest release.

It's true that you shouldn't deploy experimental papermc builds, but the update check in vane will find the new version and send a notification. If the update messages annoy you, you can of course disable them in the core config.

**Comment by cfouche3005** [comment]
ok thank for your very fast reply
