### ISSUE TITLE
Missing translations in Vane 1.9.0

### ISSUE THREAD

**Issue by fjgaldo** [oddlama/vane#152]
Vane: 1.9.0
ProtocolLib: v5.0.0-SNAPSHOT-b567
Minecraft: Paper 1.19-git-Paper-13

Whenever I join the server I get this message:

![message](https://user-images.githubusercontent.com/5272743/173549906-480f1da5-afc3-4b58-85ee-14c36becd5df.png)

Already tried to remove the server-resource-pack to prompt its redownload but it is still displaying the missing join message.

If I change `client_side_translations` to `false` in `vane-core/config.yml`, the message is displayed properly.

**Comment by oddlama** [comment]
Unfortunately the issue still persist. It is tracked by dmulloy2/ProtocolLib#1683.
