### ISSUE TITLE
Vane enchantments will not load, other plugins will

### ISSUE THREAD

**Issue by JJDelisle** [oddlama/vane#154]
There is no error returned in the logs, and it also seems that the permissions plugin is missed as well. They aren't even mentioned in the console.

**Comment by oddlama** [comment]
I'm sorry, if they are not even mentioned in the logs that 100% points to an installation error or issue with your system. Before any logic of the plugins even comes into play, they will be mentioned in the logs by the plugin loader.

Can be a lot of things. Maybe a file permissions issue, or the files were not completely downloaded, or a previous error in your logs.

**Comment by oddlama** [comment]
Feel free to comment here if you gain additional insights.
