### ISSUE TITLE
[Bug] vane-portals error when trying to bind a portal to terminal on 1.19.1

### ISSUE THREAD

**Issue by ItzPeto** [oddlama/vane#156]
vane-portal errors out when trying to bind a portal to the terminal

https://pastebin.com/GB8vB4Mt

MC: 1.19.1 (Purpur)
Java: 17.0.1

**Comment by oddlama** [comment]
vane is not updated for 1.19.1 yet. You will experience errors when running on an unsupported version. I'll see if I can put out an update.

**Comment by oddlama** [comment]
I've released vane 1.9.5 for 1.19.1. I'd be great if you could report back whether it fixed your problem :D

**Comment by ItzPeto** [comment]
Yes it's working! Thank you so much! I'm closing this issue.
