### ISSUE TITLE
[Docs]: Add a CONTRIBUTING.md.

### ISSUE THREAD

**Issue by MagnusHJensen** [oddlama/vane#159]
I was trying to just make a small PR, and help this project, but there was no setup guide, nor any instructions on how the project works. Or just a 1-2-3 for running the development server. 

That could definitely be helpful both for me and for any future people, wanting to contribute :D

**Comment by oddlama** [comment]
Thanks for the suggestion! This would certainly help, I'll try to collect some information. I guess especially the internals could use some explaining, as vane has it's own config and resource pack generator which might be confusing at first.

Building should actually be as simple as just running `./gradlew build`. I then manually copy the jar files to my testserver in the server start script. There is `./gradlew runServer`, but as you apparently already noticed, this seems to have issues right now.
