### ISSUE TITLE
Add some features of TweakIn

### ISSUE THREAD

**Issue by ahdg6** [oddlama/vane#16]
Spigot: https://www.spigotmc.org/resources/tweakin-1-16.93444/

Because vane has a better customization and modulation system,I'w like to use vane instead of TweakIn,but vane is lacking some features that TweakIn have,I have to install both of them.I do hope to see that vane can add some features of TweakIn.
Anyway,thank you for creating such an wonderful plugin.

**Comment by oddlama** [comment]
Thanks for the suggestion, I'll definitely have an in-depth look at it after updating to 1.17 (which unfortunately is still blocked by waiting on a stable Paper release). It certainly has some promising ideas, and some features like the in-inventory openable shulkerboxes were already on the wish-list. Are there any features you are especially keen on having?

**Comment by oddlama** [comment]
Now tracked by #120 #121 #122 #123 (mainly).
