### ISSUE TITLE
custom messages not working

### ISSUE THREAD

**Issue by MojoBlaster** [oddlama/vane#161]
Custom messages are not properly shown, even though the language has been specified. Instead, it will show messages like
"vane_bedtime.player_bed_enter".
I don't need the chat functions, so I just disabled it in the vane admin config, but there is no way to disable it for the vane bedtime plugin.

Using git-paper-132 and vane core, admin, permissions and bedtime version 1.9.6. The only other plugins installed are ProtocolLib v5.0.0-SNAPSHOT-b598 and ActionHealth v3.5.8.

Let me know if you need any additional information.

**Comment by oddlama** [comment]
Hmm, did you disable client_side_translations? If not, is the resourcepack properly loaded?

**Comment by MojoBlaster** [comment]
I am an idiot. Should've read the whole configs. Disabled client_side_translations and that fixed the issue.
I disabled the resource pack stuff as I don't want my players to have to install a pack.

Sorry for the inconvenience and thanks for the quick help!

**Comment by oddlama** [comment]
No worries
