### ISSUE TITLE
[Meta] Publish to Modrinth 

### ISSUE THREAD

**Issue by RozeFound** [oddlama/vane#172]
Modrinth is open platform for distributing modifications for Minecraft, lately they added support for plugins, so I guess vane would fit in there.

**Comment by oddlama** [comment]
Awesome, I love Modrinth and I've actually been waiting for this for ages. Thanks for reminding me of this!
I've published it [here](https://modrinth.com/plugin/vane), but it may take some time until it has been processed by Modrinth.
