### ISSUE TITLE
[Bug] vane-trifles - North Compass rotate in the wrong direction when in the left side of the screen

### ISSUE THREAD

**Issue by ThisIsAreku** [oddlama/vane#174]
When a north compass is on the off-hand (or the main hand if playing left-handed) it points to the wrong direction
![2022-09-23_16 49 28](https://user-images.githubusercontent.com/370207/191989521-4205b3d0-87ca-456d-850d-6c1f386050ed.png)

Vane version: v1.10.0
Minecraft version: 1.19.2
Server version: git-Purpur-1786 (MC: 1.19.2)

**Comment by oddlama** [comment]
I just copied what I found from the original compass, can you check wether the classical compass works differently? If not, then there isn't anything I can do unfortunately :/

**Comment by Serial-ATA** [comment]
The vanilla compass does flip the texture:

![image](https://user-images.githubusercontent.com/69764315/192123831-4f3b9262-e7de-4e5f-a88c-f345ca53d588.png)

**Comment by oddlama** [comment]
Lol I legit copied the datapack code from the original compass. I'll need to investigate where the flipping happens. If it's on the client side we might have bad chances.
