### ISSUE TITLE
chat message formatter error

### ISSUE THREAD

**Issue by AmeLooksSus** [oddlama/vane#179]
<img width="572" alt="Screenshot 2022-12-05 at 9 23 31 PM" src="https://user-images.githubusercontent.com/119868491/205684340-9c901aaa-98e2-4ffe-add9-3649d813d9b8.png">
 I even deleted the plugin and installed but its still showing like this to everyone who joins or leaves the server, same thing happens for all chat formatting like switching gamemodes

**Comment by oddlama** [comment]
I don't know what exactly you did, but this is certainly user error and related to the texture pack not being applied.

**Comment by AmeLooksSus** [comment]
yeah, I'm sorry, it was one of my resource packs that was causing the problem.
