### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by BaltimoreGamingYT** [oddlama/vane#18]
So I added a couple vane modules to my plugins folder (core, admin, bedtime, enchantments, portals, and trifles) but they don't appear to be in the server

When i launch the server and do /plugins all it shows is the invsee plugin i have, none of the vane modules are there.

 If it helps I don't think any configuration things generated when i launched my server with the vane plugins.

**Comment by oddlama** [comment]
This isn't a problem with vane but with your server setup. To find the error you have to examine your logs.
Also this isn't a support channel for server setup problems but for specific issues with the plugin, so if you need help setting up your server, I'd like to kindly point you to the official papermc forum or discord.
