### ISSUE TITLE
Feature for Portals

### ISSUE THREAD

**Issue by Bossbirdyman51** [oddlama/vane#19]
Hi ;)

Thanks for you great job, i like your plugin but i want to use Portals to transporte blocks it's possible ? For example i drop blocs / items on portal and my friend received it.
Minecart work with rails ? ^^

Thanks you

Dear,
Bossbirdyman
Ps : Sorry for my language i am french.

**Comment by oddlama** [comment]
Regarding the items: Unfortunately, papermc doesn't expose any events that I can use to detect items touching the portal area, so unless this is implemented by the folks over at papermc.io, there isn't much I can do (but I like the idea).

Minecarts on the other hand should be possible. I can have a deeper look into this the next time I have time to work on the plugin :)

**Comment by oddlama** [comment]
This issue has been merged with another one and will be tracked via issue #37.
