### ISSUE TITLE
Not really an issue: 1.19.4 Update?

### ISSUE THREAD

**Issue by razielaka** [oddlama/vane#191]
Thanks for your great plugin.
Is an update for 1.19.4 on the agenda?

**Comment by oddlama** [comment]
For sure! We'll just have to wait a little longer (1-2 days) until a stable paper release is out.

**Comment by oddlama** [comment]
FYI: Internal update is done. I'll still have to add some promised changes, then a new version will be released.

**Comment by oddlama** [comment]
Done :)
