### ISSUE TITLE
DOC Suggestion | Papyrus scroll craft missing on DOC

### ISSUE THREAD

**Issue by JonathanAriass** [oddlama/vane#204]
When reading the DOCs on  `https://oddlama.github.io/vane/` I found that I had no info on how to craft a `Papyrus scroll`. It should be fine to have more information about this craft. I know you can see the craft inside the game when you have the materials, but I had to look the source code to know which materials were needed for the craft.

Thanks and sorry for the inconvenience

**Comment by TDuffinNTU** [comment]
I had no idea it was craftable until I saw this issue!

**Comment by oddlama** [comment]
Recipe has been added in the meantime
