### ISSUE TITLE
[TRIFFLES] Duplicating items with the pouch

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#206]
Vane versions: 1.12.2
Paper version: paper-1.20.1-18

Here is an explanation in GIF:
![CleanShot 2023-08-01 at 09 39 29](https://github.com/oddlama/vane/assets/37812331/cc1c32f5-d818-4311-b75f-83dc9816f199)

**Comment by oddlama** [comment]
Thanks, I'll push a fix right now

**Comment by WaxenSs** [comment]
I think the problem may also be present for the bag

**Comment by oddlama** [comment]
Both should be fixed by this

**Comment by WaxenSs** [comment]
Nice thx !
