### ISSUE TITLE
Plugin Compat - only unfreeze registries right before adding stuff

### ISSUE THREAD

**Issue by Machine-Maker** [oddlama/vane#208]
vane-core unfreezes registries (and sets the intrusive holder cache) when the core plugin's constructor is initialized. This happens before any other plugin's onEnable is called which could be before vanes' onEnables are called which add stuff to the registries. Any plugin that has their own onEnable called inbetween that does something which causes the registries to be re-frozen will interfere in vane's ability to add stuff to the registries.

**Comment by oddlama** [comment]
Enchantment registries are now unfrozen each time as suggested beginning with vane 1.13.0.
Sorry that it took so long to add this trivial thing.
