### ISSUE TITLE
[PORTALS] Duplicating items with the portal

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#209]
Vane versions: 1.12.3 Paper version: paper-1.20.1-108

- Possibility of duplicating items with a smaller hitbox than a decorating block (works with lanterns, for example) 
- Amethyst can also be destroyed (by mining the block underneath) (bell, door, bed, pointed dripstone, cactus likewise) 
- Not yet tested, but be careful not to be able to duplicate chests or shulker boxes as well. 
- The pistons work, by activating it and undermining the head of the piston, this allows it to be duplicated

**Comment by oddlama** [comment]
The next version for 1.21.3 will only allow full blocks to be used in decorations. This prevents cactus, doors, bells, pretty much anything that might break. Pistons are the only full block that I found which would still be a problem, if you know of any other problematic blocks that you want on the default blacklist, let me know :)
