### ISSUE TITLE
Can't Custimoze Messages

### ISSUE THREAD

**Issue by NyhmsQuest** [oddlama/vane#21]
No matter what I try and do I just can't seem to customize the messages, doesn't matter what I change it to it just always shows the default messages.

**Comment by oddlama** [comment]
I will need more information to help you. What messages are you talking about explicitly? Are you on 1.17? What have you tried exactly?

**Comment by NyhmsQuest** [comment]
I'm on 1.17 and I tried changing the values for player_chat_format, player_join and player_quit in the vane-admin folder inside the lang-en-yml and even making my own lang-custom.yml.
Personally I'd prefer to use another plugin to handle those, but I can't even seem to disable just that feature so I tried to customize it to my liking.

**Comment by oddlama** [comment]
I'll include an option to disable them in the next update.
Nontheless, you should be able to modify them. If you are using the english default, this should suffice:

1. copy `plugins/vane-admin/lang-en.yml` to `plugins/vane-admin/lang-en-custom.yml`
2. edit `plugins/vane-admin/config.yml` and set `lang: "en-custom"`

**Comment by NyhmsQuest** [comment]
I tried exactly what you just said and that didn't change anything.
It's fine, I'll wait for the update with the option to disable any chat modifications.

**Comment by oddlama** [comment]
Ah, have you regenerated the resource pack afterwards? That's necessary, as all translated messages are processed on the client.
Just repeat the steps as shown in the installation guide (execute `vane generate_resource_pack`, host it or distribute it, and update sha1 in config if necessary)

**Comment by NyhmsQuest** [comment]
Ah I see, yeah I never did that before. This is the first time I'm working with resourcepacks so I had no idea the resourcepack controlled the messages, that's very new to me. Can I ask why you've made it like that and no the traditional way?

**Comment by oddlama** [comment]
Primarily the resource-pack is needed for the custom item textures, and while I was at it I also added the messages because this allows each player to select the language separately.

**Comment by NyhmsQuest** [comment]
Do you think it would be possible for an option to choose between resourcepack messages or the traditional way? Of course along with the option to disable vane from modifying chat

**Comment by oddlama** [comment]
Should be possible, I can include also include an option to do this in the next update.

**Comment by oddlama** [comment]
Implemented and released with vane-1.2.2
