### ISSUE TITLE
[TRIFLES] Bug grass path

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#212]
When a player already has speed on a grass path and leaves the grass path, the speed is removed from the player. The grass path speed must override the player's base speed, and must therefore reset the player's old speed counter.

**Comment by oddlama** [comment]
The grass path speed is intentionally set as an effect so it doesn't stack to ridiculous speeds and so we don't have to handle any edge cases. Modifying player base speed is asking for trouble since there is no sensible API to distinguish our modifications from other plugins' modifications.
