### ISSUE TITLE
Rod labeling issues

### ISSUE THREAD

**Issue by Killakooo** [oddlama/vane#214]
When I add a ”grappling hook“ enchantment to the rod and then add bait to it, the ”grappling hook“ enchantment label changes, like this
I used the chinese language resourcepack on my own 1.20.1 JAVA server
I would appreciate it if you could help me!

<img width="650" alt="image" src="https://github.com/oddlama/vane/assets/138203531/0bab95fd-5d17-4441-830d-5d18a9d5144d">

**Comment by oddlama** [comment]
You seem to be using another plugin that is modifying the lore (text) of an item. That other plugin is responsible for that - it converts our translated components into just text, so your client doesn't know it needs to substitute that. Please raise this issue to the creator of that other plugin. They need to use something like `adventure.kyori.net` to modify the lore without affecting existing lines from vane.

**Comment by Killakooo** [comment]
Thank you for your help and i'll check out :)
