### ISSUE TITLE
Player in bed count broken. (Paper-194 1.20.1)

### ISSUE THREAD

**Issue by GrimPlayzs** [oddlama/vane#219]
Not sure if it was me updating to the latest 1.20.1 paper build or updating the plugin that caused the issue but here are the screenshots.
![2023-09-23_18 42 11](https://github.com/oddlama/vane/assets/89351648/6de72936-70cc-48ba-b2b9-31df4ae148f9)
![2023-09-23_18 42 14](https://github.com/oddlama/vane/assets/89351648/b20df262-495b-4af6-b63e-82d5ae6deeb8)

**Comment by oddlama** [comment]
Do other strings work fine? For example craft yourself any vane item (e.g. a sickle), check whether the name is also not showing correctly.

If the freshly (!) crafted sickle has the correct name, then this is a bug. If it has the same issue as above, you are missing the resource pack or a related setting.

**Comment by GrimPlayzs** [comment]
Since you mentioned the resourcepack made me realize that I completely forgot to have the resource pack on my client since I usually just downloaded the pack off the server and put it in my resourcepack folder to prevent the Mojang loading screen from coming up every time I join.
