### ISSUE TITLE
Problems with resourcepack

### ISSUE THREAD

**Issue by DSLZL** [oddlama/vane#237]
When I added a resource pack as a resource pack for the server, vane resent its own resource pack, replacing the resource pack I had set up, could there be a module that could manage the resource pack, or a solution to this problem

**Comment by oddlama** [comment]
Adventurelib recently added support for multiple resource packs. So in the future (hopefully next version or the one after that) i believe it should be possible to have multiple resource packs that don't interfere with each other. But it'll take some time until I can implement it.

For now you'll have to either merge the packs yourself, or distribute one of them ahead of time to your clients.

**Comment by DSLZL** [comment]
> Adventurelib recently added support for multiple resource packs as upstream support was added to Minecraft 1.20.3. So in the future (hopefully next version or the one after that) i believe it should be possible to have multiple resource packs that don't interfere with each other. But it'll take some time until I can implement it.Adventurelib 最近增加了对多个资源包的支持，因为上游支持已添加到 Minecraft 1.20.3 中。所以在未来（希望是下一个版本或之后的版本），我相信应该可以拥有多个互不干扰的资源包。但是我需要一些时间才能实现它。
> 
> For now you'll have to either merge the packs yourself, or distribute one of them ahead of time to your clients.现在，您必须自己合并包，或者提前将其中一个包分发给您的客户。

Understood, thank you for your answer, I hope this issue will be resolved soon

**Comment by DSLZL** [comment]
ok
