### ISSUE TITLE
Chat message formatting not outputting formatted messages in-game

### ISSUE THREAD

**Issue by matthew-ashley-ctl** [oddlama/vane#24]
Running PaperMC 1.17.0 with the following plugins:
- ProtocolLib
- vane-core
- vane-admin

Issue description:
Any message that would be formatted appears as a "variable-like" message in-game, but displays correctly in the server log. 

Messages in-game:
![image](https://user-images.githubusercontent.com/40571495/124331662-4918d780-db55-11eb-846f-9ac0b4865df4.png)

Messages in server log:
![image](https://user-images.githubusercontent.com/40571495/124331714-68176980-db55-11eb-9cfe-665fa7eda872.png)

I did my best to try to ensure this wasn't a permissions issue, but I'm new to setting them up. Apologies if that's all this is.

**Comment by borkmaster12** [comment]
After disabling the chat_message_formatter option in vane-admin, I can see chat messages in-game again, but the in-game output of /permission list groups experiences a similar issue:
![image](https://user-images.githubusercontent.com/46276086/124333553-2f2dc380-db5a-11eb-81f6-1214fa662ff2.png)

The output in the server console is formatted and displays correctly:
![image](https://user-images.githubusercontent.com/46276086/124333598-4ec4ec00-db5a-11eb-94de-0ec7cddfed22.png)

**Comment by matthew-ashley-ctl** [comment]
I see now that this is due to the resource pack not being delivered to the client. I haven't yet achieved a solution to delivering the file, but I can see that this is user-error. Closing.

**Comment by oddlama** [comment]
Depending on your setup, you have some options on how to deliver it. The easiest being copying it to the client manually. Otherwise, you will need some kind of webhost to host it, which will make delivery easy but is harder to maintain.

**Comment by matthew-ashley-ctl** [comment]
I ended up hosting the file on Google Drive, changing access permissions to "Anyone with the link", and using a utility to convert the share link into a direct link.
