### ISSUE TITLE
Gold sickle not working

### ISSUE THREAD

**Issue by lcf716** [oddlama/vane#25]
Hi,

When i try to use the gold sickle on wheat it show the message as below. However using wood sickle is fine. Thanks in advance!

![image](https://user-images.githubusercontent.com/22512401/124686495-d10c3200-df05-11eb-84ab-4bf48fcc8c9f.png)

**Comment by oddlama** [comment]
This is not related to vane. It seems like you have another plugin running that intercepts right-clicking with the base type of this item (golden hoe), and cancels the events for all plugins.
