### ISSUE TITLE
Please allow me to use a different chat suite

### ISSUE THREAD

**Issue by PaixD** [oddlama/vane#26]
I have looked through the configs and I see no way to turn of Vane Chat but I need Vane Admin for creeper explosion rollback unfortunately.

I tried looking for a discord/discussion place for this plugin but I have found nothing so far, so as a last resort, I have opened an issue here

**Comment by oddlama** [comment]
I'm not entirely sure what you mean by vane-chat, but i suspect you are referring to the chat message formatting which makes player messages shown differently.

Are you running the latest version? If so, you should be able to disable it with the option `chat_message_formatter`.

**Comment by PaixD** [comment]
The latest version doesn't work with 1.16.5 sadly

**Comment by oddlama** [comment]
Unfortunately I can't backport every new feature to old versions. It just isn't worth the effort, I'm sorry.
May I ask what is holding you back from updating?

**Comment by PaixD** [comment]
Most of my plugins don't work on 1.17, I tried but it seems like I will have to find replacements for those plugins before then.. but otherwise if that's the case is there a possible workaround?

**Comment by oddlama** [comment]
I highly recommend you to update sooner or later, as you won't receive any updates for your server software or your plugins anymore (so no bugfixes no security updates). That doesn't seem desirable to me.

Also, what do you want to workaround? If you just dislike the visuals of the chat, then this isn't per se something that can be worked around. If it causes an incompatibility to another plugin, there might be a workaround depending on the offending plugin, but you'd have to post some details.

**Comment by PaixD** [comment]
Like for example, before adding vane-admin, another chat plugin (VentureChat) was running the chat service and I'd like it to keep doing so, that's the workaround I was referring to

**Comment by oddlama** [comment]
In that case I fear you need to update to 1.17 to get the functionality you require.
