### ISSUE TITLE
[FEATURE REQUEST]Add support for the purpur side of 1.20.1.

### ISSUE THREAD

**Issue by AOKAOKA** [oddlama/vane#262]
It's a pity that I didn't run successfully on the server with purpur core. Does it not support purpur?

**Comment by oddlama** [comment]
Officially we target PaperMC but AFAIK Purpur builds upon PaperMC so in theory it should be compatible. If you want us to have a look at it, please upload your logs.

**Comment by TarkinMX** [comment]
I run my server on purpur and have no issues with vane. I'd like to see what the issue is that OP is having as well.

**Comment by oddlama** [comment]
Closing this as I cannot reproduce the error. Feel free to repost if you have logs.
