### ISSUE TITLE
[BUG] Ancient Tome of the Gods can't be used again after disenchanting it via Grindstone

### ISSUE THREAD

**Issue by GuilhermeAgR** [oddlama/vane#275]
When using a looted Ancient Tome of the Gods with an enchantment in the grindstone in order to remove the enchantment and re-use the book in another enchantment, the book becomes unusable for crafting other enchantments.

This is because when disenchanting an enchanted Ancient Tome of the Gods leaves it as a "minecraft:enchanted_book" item, while the naturally crafted one is a "minecraft:book".

When you use a regular minecraft enchanted book on a grindstone, however, it goes back to being a regular book. A vanilla Enchanted Book shares the same item type ("minecraft:enchanted_book"), but after grinding it, it goes to ("minecraft:book").

I believe this is a minor oversight that could be fixed. If I find a Ancient Tome of the Gods with an enchantment I already have/don't need and try to disenchant it, the book goes back to normal "non-enchanted" book, but it is still an enchanted book. This means I can't recycle it into enchantments that I really want, but theoretically should be possible.

![image](https://github.com/user-attachments/assets/f9b6a9a3-f551-46c6-b167-6b405a41ec37)
Example of naturally crafted Ancient Tome of the Gods. Notice the item tag/name is "minecraft:book".

![image](https://github.com/user-attachments/assets/9137d9f3-5821-4a83-8c65-dd38139a64e2)
Example of a disenchanted Ancient Tome of the Gods. Notice the item tag/name is "minecraft:enchanted_book".

![image](https://github.com/user-attachments/assets/b3b7ac70-5fa9-4bc6-ab82-befd9b36dc1d)
Example of a Vanilla Enchanted Book which has been disenchanted via a grindstone. It goes back to being a "minecraft:book".

![image](https://github.com/user-attachments/assets/3ccac356-f484-4a2b-be38-5668250610f1)
Step 1 of disenchanting

![image](https://github.com/user-attachments/assets/e92a77b6-0aba-4cea-a516-3a3279512f8f)
Step 2 of disenchanting

**Comment by GuilhermeAgR** [comment]
I am not sure if this is relevant or not, but when I first had disenchanted the _AtotG_, it had lost the "enchantment glint", characteristic of enchanted items. It was still an enchanted book, but it had lost the "glint/glow" effect.

When I spawned another _AtotG_ via commands, however, it had this glint/glow and somehow the old book also got it back. I am not sure how, since I had put it away in a chest (so the items wouldn't stack, which now I know they wouldn't, because minecraft:enchanted_book don't stack, only minecraft:book).

As far as I could tell, this was only a visual issue and it had no effect in recipes not working. The whole issue seems to originate in the fact of the books being different items (minecraft:enchanted_book vs minecraft:book).

**Comment by oddlama** [comment]
A fix for this will be present in the upcoming 1.21.3 release
