### ISSUE TITLE
[Bug] Problems when generatating Vane resource pack (1.21.3 and 1.21.4)

### ISSUE THREAD

**Issue by GabFran** [oddlama/vane#277]
Executing /vane generate_resource_pack in the latest Vane version (1.16.0) gives an error. A resource pack is generated in the server folder, and although it loads, custom item models do not work.

The error is given by the following log

https://mclo.gs/hgmAcFQ

**Comment by GabFran** [comment]
Still occurs in latest 1.21.4 update

**Comment by oddlama** [comment]
What changes have you made to the core config? I can't reproduce this with the defaults.

**Comment by oddlama** [comment]
In any case, you can also just use the pregenerated resource pack from [here](https://github.com/oddlama/vane/tree/main/docs/resourcepacks), they will have the same content as a manual generation except if you changed language files.

**Comment by GabFran** [comment]
> What changes have you made to the core config? I can't reproduce this with the defaults.

The only change I have done is disabling automatic distribution https://mclo.gs/Q1u3o3w

The pregenerated does not work properly either. The issue is that custom textures do not load.

**Comment by oddlama** [comment]
Hmm, that's interesting. Since the pregenerated RP works for everyone else, there must be something unique to your setup. Or maybe your players are not using the vanilla java client that does something differently.

**Comment by GabFran** [comment]
I have just tested in a clean vanilla install, so it must be server-side.

**Comment by GabFran** [comment]
Fresh vanilla 1.21.4 install, clean install of paper 1.21.4 build 15, running only Vane and ProtocoLib: https://mclo.gs/IELnmoO

Resource pack shows as wrong version:

![image](https://github.com/user-attachments/assets/7f2e6424-b0c1-49a5-a315-1e99ca5ecdbc)

Custom models do not load, although custom enchantments and etc do work as intended:

![image](https://github.com/user-attachments/assets/b0dac7c7-4de6-47e8-86ac-5a4532f2e171)

Odd, huh?

**Comment by AlexRespawned** [comment]
> Fresh vanilla 1.21.4 install, clean install of paper 1.21.4 build 15, running only Vane and ProtocoLib: https://mclo.gs/IELnmoO
> 
> /vane generate_resource_pack does not give an error, however issue persists.
> 
> RP shows as wrong version:
> 
> ![image](https://private-user-images.githubusercontent.com/24740211/397561572-7f2e6424-b0c1-49a5-a315-1e99ca5ecdbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MjgyMTgsIm5iZiI6MTczNDgyNzkxOCwicGF0aCI6Ii8yNDc0MDIxMS8zOTc1NjE1NzItN2YyZTY0MjQtYjBjMS00OWE1LWEzMTUtMWU5OWNhNWVjZGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAwMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTRkYmYyMGVlZThiOWUxNWIxYzYwY2Y4NjE3ZDU1MzdkOWY2YzQwZTc4YTg1M2UzN2E3Njk2MjNmMDMzYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rjnht8pOqOjWFeSDYDH1oQDNo8-jy0F58NVGNdMQ79U)
> 
> Custom models do not load, although custom enchantments and etc do display as intended upon enabling the RP.
> 
> ![image](https://private-user-images.githubusercontent.com/24740211/397562596-b0dac7c7-4de6-47e8-86ac-5a4532f2e171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MjgyMTgsIm5iZiI6MTczNDgyNzkxOCwicGF0aCI6Ii8yNDc0MDIxMS8zOTc1NjI1OTYtYjBkYWM3YzctNGRlNi00N2U4LTg2YWMtNWE0NTMyZjJlMTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAwMzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNWE3OGQwMTUxMzcxZDlkMDE5NjRjZmQxNDNkMmYzNTg4NmU2NDJkNDc2ODgxNWMwY2QyMjkxYmVjYjM0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ILhFZrYgfIMw9n9PH6Lzmh1qEKkMTgp6ceiNl6tG72Q)
> 
> Odd, huh?

Having the exact same issue, same versions of MC, Paper, and Vane as you. Custom models do not show

**Comment by oddlama** [comment]
I might have a lead as to what could cause this. Will update when I find out more.

**Comment by oddlama** [comment]
Can you retry with the latest version? Might have been PEBCAK from my side. https://github.com/oddlama/vane/releases/tag/v1.17.2

**Comment by AlexRespawned** [comment]
> Can you retry with the latest version? Might have been PEBKAC from my side. https://github.com/oddlama/vane/releases/tag/v1.17.2

That solved the issue for me! Models now show correctly

**Comment by GabFran** [comment]
Resource pack works fine now, cheers!
