### ISSUE TITLE
Unable to launch vane-portals v17.1

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#282]
It is no longer possible to launch vane-portals since 1.17.1. It still detects v1.16.0 even though I have 1.17.1. 

`[15:18:57 INFO]: [vane-portals] Enabling vane-portals v1.16.0 [15:18:57 ERROR]: Error occurred while enabling vane-portals v1.16.0 (Is it up to date?) `

**Comment by oddlama** [comment]
This seems like a CI caching issue, I've retriggered the artifact upload. It should (in theory) only affect the message that is displayed, the code should be 1.17.1 already.

The artifacts of 1.17.1 are already updated.

**Comment by WaxenSs** [comment]
That's it for vane-portals thanks, the other plugins are still displayed as version 1.16.0, but that doesn't make them crash.

**Comment by oddlama** [comment]
with the current artifacts I get 1.17.1 on all plugins, are you certain you replaced all files?

**Comment by WaxenSs** [comment]
Yes, I've just rechecked, all Vane plugins are in version 1.17.1. However, I don't use all the plugins. I use core, portals and trifles. Portals shows the correct version but not the other 2.

```
[15:53:23 INFO]: [vane-core] Enabling vane-core v1.16.0
[15:53:23 INFO]: [vane-portals] Enabling vane-portals v1.17.1
[15:53:23 INFO]: [vane-trifles] Enabling vane-trifles v1.16.0
[15:53:23 INFO]: Preparing level "world" ...
```

**Comment by oddlama** [comment]
What I meant was that the downloads on the 1.17.1 page on github have been updated for all plugins so you need to redownload them all

**Comment by WaxenSs** [comment]
Oh ok it's good sorry :)), thx
