### ISSUE TITLE
Double door behavior is wrong in certain edge-cases.

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#38]
Sometimes two doors with non-opposing hinges are opened, especially the door behind door scenario sometimes has that bug. Rewrite the double-door opening logic to correctly handle all doors.

**Comment by ryantheleach** [comment]
Example of the 'door behind door' buggy scenario:

![image](https://user-images.githubusercontent.com/141554/147717893-da56c7fe-911c-43b6-9f31-94aad33be23f.png)

**Comment by ryantheleach** [comment]
@oddlama Should this be closed, or maybe consider a tag for 'fixed in next release?'

**Comment by oddlama** [comment]
it would be closed automatically if i'd finally do the merge from develop into main branch xD

**Comment by oddlama** [comment]
Actually I could do that, but I'd like to get some more things in before the release.
