### ISSUE TITLE
Add a tombstone system

### ISSUE THREAD

**Issue by vale075** [oddlama/vane#41]
Hello, would it be possible to add a tombstone system? When someone dies all its items are collected in a chest.
The reason I ask here is that it would need to be compatible with world_rebuild in case you die of a creeper explosion and also with the Soulbound enchant.
It could have dynmap integration.

I think it would be a great addition to this already absolutely amazing plugin!

**Comment by oddlama** [comment]
Thanks for the suggestion! I'll have to think about how this would be doable while maintaining a vanilla feeling.
I can see that this is (near) impossible to be implemented correctly by another plugin. You are absolutely right that world rebuilding and soulbound could be issues if this was implemented by another plugin.

For world rebuilding, currently a chest placed on a block that will be rebuilt later will cause the chest to be
naturally destroyed later (i.e. dropped with contents), which would be bad in case of tombstones. The only solution I can see is to never place the chest where a block will be rebuilt. (Hint to self: explosion and death event order may be critical here)

I also see some other corner cases. Feel free to comment on them if you've got any ideas or suggestions:

1. A player falls in the void
2. A player dies mid-air (but with ground somewhere below)
3. A player dies on top of the highest possible block and there is no space to put the chest
4. A player dies on a tombstone
5. A player dies inside a block made of something (cobweb, water (could replace), snow, sign)
6. A player dies in a protected region (spawn, vane-regions)

Dynmap integration would certainly be possible although I could also imagine this cluttering the map a little too much if players don't remove their tombstones. Also I can see scenarios where tracking existing tombstones could
become problematic (not impossible, just not trivial to implement).

(Note to self again: Optionally tombstones could be protected such that only their owner may retrieve them.)
I'll have a look at this again when I have time to implement it.

**Comment by vale075** [comment]
PS: I wrote an essay, sorry XD

Wow!
First of all, thank you very much for your detailed response! 

#### Vanilla feel
For the vanilla feel, you are right. This would be more of a quality of life improvement, like disabling creeper griefing has it can be very frustrating for a player to die and lose everything.
The chance of losing everything if you die can make the game more thrilling but I feel it can generate a lot of frustration and be the reason you quit the game, after losing a lot of stuff accidentally.

To try and keep a more vanilla feeling we could try to find a consequence to getting back your stuff:
- It could need an enchant to happen but this would prevent it in early game at the time it is most needed, the same thing for totems. 
- You could maybe have to buy back your stuff, trade for something like a skull a bit like for heads, but again this would be limiting in early game.
- You could maybe make it "unperfect" somewhat so dying doesn't become "easy". There could be a "degradation" mechanic where as time goes by the number of items retrievable from when you died goes down (you could still choose which ones) until the tombstone eventually disappears completely. This would make stuff retrieval less random hoping it hasn't de-poped while still keeping the fear of losing things. And would also resolve the "there are tombstones everywhere" problem on the Dynmap as they would simply disappear over time.

#### The mechanic itself
I don't know if you can do custom blocks with plugins, but it could be a sort of slab buried one block in the floor. For placing, you would look up the player's death position and replace the first solid block that appears underneath him (counting lava has a block, for water you could make it "float" or sink down to seafloor) except if it is bedrock in what case you place it on top of the bedrock.
After being cleared out or if left out for too long (see idea on tombstone slowly decaying) the tombstone would simply be destroyed and the block it replaced would get brought back exactly like for the explosion rebuilding already present in the plugin.

For the cases you talked about:
- This should resolve points 2 and 3 already.
- For point 5,  if he was inside a block it would simply replace the block underneath if not bedrock, and if the block was solid well the tombstone will be buried underground, it shouldn't matter?
- For point 6, the block it replaced would just reappear when the tombstone is destroyed and has anyone can loot what's inside the tombstone, anyone can make it disappear. You could still add the option to deactivate them in certain regions.
- For point 1 (void) I'm not sure. The only place you are supposed to encounter void is in the end but I'm tempted to say you could make it irretrievable has you should be at an already advanced level at that point and in vanilla Minecraft there would be no way to get it back anyway. The only problem would be custom maps that incorporate void in the design (skybloc, etc...) but those already don't feel vanilla anyway.
- For point 4, you could:
  + make it replace the first one that would reappear after it is destroyed (bad idea XD)
  + make it "merge" with the first one, the decaying of the first one would be reset
  + make them spawn on top of each other/next to each other.

#### Dynmap/Tombstone retrieval
For the Dynmap integration I was thinking of the server I have with my friends where everybody is friendly, so in that scenario it wouldn't be a big deal. But it should definitely be optional (if it even exists in the first place) for bigger servers where griefing is allowed.
This asks the question of how you would find a tombstone if you didn't use Dynmap.
In that case you could maybe use a special compass that indicates the direction and appears in the inventory of the person who died that could be passed to other people and disappear with the tombstone. Then a cool mechanic would be to be able to craft a tombstone finder that indicates the position of the nearest tombstone for big servers and people would be some sorts of grave diggers. But now I'm going a bit far XD


All of the above are ideas, do whatever you feel fits best the plugin if you even feel like implementing something. The plugin is absolutely great and I love the vanilla feeling it keeps. Thank you!

**Comment by oddlama** [comment]
Hi! After careful consideration I decided that this is unfortunately too far out-of-scope for vane. I can't help it but feel like it's adding too much on top of vanilla and would be better suited for a separate plugin. But I like the idea very much and think it might be a cool option to have. There is nothing that requires vane to implement this feature, and a gravestone plugin could easily add support for vane without vane doing anything. As there already exist a plethora of gravestone plugins, I'd much rather see support for vane added in one of these popular plugins.

Compatibility with vane would be easily achieved: The tombstone can be excluded from the block destroy event before vane processes it (other plugin has to use _lower_ priority on the explosion event, I know, sounds wrong but is right), if it even is a part of it. It just needs to make sure that it isn't inside a block that was exploded, so that vane doesn't override it. Soulbound items can be excluded by examining the enchantments NBT and looking for `vane_enchantments:soulbound`. I'd be willing to implement an API for this if necessary.

I might open an issue on one of these plugins and link to this issue. With a bit of luck they also like vane and are willing to implement support for vane. (If anyone is coming from a gravestone plugin, I'm available to help with implementing compatibility over on [discord](https://discord.gg/RueJ6A59x2), just ping me)

**Comment by oddlama** [comment]
I've opened [an issue](https://gitlab.com/ranull/minecraft/graves/-/issues/49) in a very popular plugin called [Graves](https://gitlab.com/ranull/minecraft/graves) regarding this. Lets see what they say :)

**Comment by ryantheleach** [comment]
I'm currently using Graves on my server, will let you know if I run into trouble, as I planned on using soulbound on my start item kits :-)

**Comment by oddlama** [comment]
Cool cool, I remember that I did test it once when I talked to the people from Graves, but couldn't identify any issues. Just let me know if anything unexpected comes up.
