### ISSUE TITLE
Website Enhancements

### ISSUE THREAD

**Issue by Zoriot** [oddlama/vane#43]
I have some things which whould be nice for the website:

- More Languages (like the ones ingame)
- Dark Mode
- More Classification about which Plugins are needed
- More Infos how the Plugins works (thats not so important)

Thanks for the great work.

Greets
Zoriot

**Comment by oddlama** [comment]
Thanks for the suggestions.

* The problem with the languages is that I don't speak any more languages fluently enough to provide a translation that I would be happy with, so I'm dependent on the community here.
* Dark mode hasn't been a priority for me, as I wanted to have good content first. But it shouldn't be too hard as I'm using a CSS framework that certainly has dark themes available, so maybe I'll look into it sometime.

At some point it might even be a good idea to scrap the single-page and replace it with a small wiki, something like a git book that is still minimal. If you have any suggestions about what you are missing content-wise, please do let me know!
