### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by TOWUK** [oddlama/vane#44]
https://github.com/oddlama/vane/blob/2a32f52124c60459e0a6e5597f69fc24b8e248e4/build.gradle#L50
with remapped sh file

**Comment by TOWUK** [comment]
https://github.com/oddlama/vane/blob/2a32f52124c60459e0a6e5597f69fc24b8e248e4/build.gradle#L37
it too

**Comment by oddlama** [comment]
It is unclear what you are asking and probably related to your second issue (#45). Please don't open multiple issues for the same problem. This isn't a forum but an issue tracker. Please try to provide the necessary information in a concise way in the top level post, and not as comments in unrelated issues.
