### ISSUE TITLE
Nobody can build when not in "admin" group

### ISSUE THREAD

**Issue by T-One** [oddlama/vane#5]
Hi,

i just installed vane on an already running server and now i have the problem that no one can build something in user/verified group, only if i add them to admin. At first i thought it has something todo with the Region plugin so i've set it to enabled: false but still only admins can build stuff. Do i miss something here?

I use the standard groups:

groups:
  default:
    - bukkit.command.help
    - bukkit.broadcast
    - bukkit.broadcast.user
  verified:
    - vane.permissions.groups.user
    - vane.permissions.commands.vouch
  admin:
    - vane.permissions.groups.verified
    - vane.admin.bypass_spawn_protection
    - vane.*.commands.*
  user:
    - vane.permissions.groups.default
    - vane.admin.commands.spawn
    - vane.admin.modify_world
    - vane.regions.commands.region
    - vane.trifles.commands.heads

No other plugins installed.

**Comment by oddlama** [comment]
My first guess would be that you are within the spawn protection radius of 64 blocks around 0,0. Only admins can build in the spawn protected area. It is defined in vane-admin, so you can disable it in `plugins/vane-admin/config.yml`.

**Comment by T-One** [comment]
Looks like this did the trick, never expected this to be in the admin config, i checked the permissions and regions...

Thanks!

**Comment by oddlama** [comment]
The admin module contains all administrative utilities. To me, global world protection and hazard protection (creeper, enderman) also fell into that category. The regions module provides the in-game regions that can be created and administrated by players, and are in fact totally different.

Purely from the naming this might indeed be misleading - sorry ;)
