### ISSUE TITLE
Duplication glitch with Vane Portals

### ISSUE THREAD

**Issue by Yoshiro0990** [oddlama/vane#51]
Heyo!
I'm using Vane Portals (latest - 1.2.2) in my Server (1.17.1), and some players have noticed this [duplication glitch (video)](https://imgur.com/a/7Z1Nzvi). We can't remove the plugin, 'cause we use vane portals instead of tpa.
Is there any way to fix this bug?
Ty 😊

**Comment by oddlama** [comment]
Thanks for the report! I will definitely have a look at this and fix it for the next release.

**Comment by Yoshiro0990** [comment]
Is it possible to know by when the plugin will be updated?
Btw, thank you for your reply and I apologize for the stress I'm putting on you, but it's a huge bug in the Server. 😁

**Comment by oddlama** [comment]
Now :)

Fixed in v1.2.3
