### ISSUE TITLE
Vane Portals

### ISSUE THREAD

**Issue by pokemonrocks9** [oddlama/vane#57]
vane portals are showing vane_portals.console_display_inactive when its not active after updating to 1.3.0/1.3.1

**Comment by pokemonrocks9** [comment]
Update:
Its doing this for everything related to text, from reloading to menus

**Comment by oddlama** [comment]
Please follow the [installation guide](https://github.com/oddlama/vane/wiki/Installation-Guide) step by step, this sounds like you are missing the generated texture pack on your client.

**Comment by pokemonrocks9** [comment]
Was the requirement for it added? Previously in 1.2.3 we didn't need it to
see the text on the portals.

**Comment by oddlama** [comment]
Unless you have disabled `client_side_translations` in `vane-core/config.yml` you need to use a resource pack. No code related to language translations has changed from 1.2.3 to 1.3.1, so this must be an issue on your side.

**Comment by pokemonrocks9** [comment]
We will try that setting and see if it fixes it. Thank you!

**Comment by oddlama** [comment]
Be careful though, some other features (such as custom items) still require the resource pack, in case you are using these features.

**Comment by pokemonrocks9** [comment]
Our main usage is portals. The resource pack requirements unfortunately
caused some users to be unable to enter

**Comment by oddlama** [comment]
Everything about the resource pack distribution and requirement is configurable and well documented in the respective config.yml files. As long as you are only using portals, a resource pack is not required. Just be sure to configure it accordingly.

**Comment by pokemonrocks9** [comment]
Much appreciated
