### ISSUE TITLE
Setting to select player orientation after taking portal

### ISSUE THREAD

**Issue by CosmicCaterpillar** [oddlama/vane#58]
Portals have been a fantastic addition to our server, but one of the minor annoyances has been with the orientation. There are a few portals we have that are built as a wall/part of a wall, and depending on the direction you are facing when walking into a portal, you will be faced into the wall/"wrong" direction. For example, we have a team vault within a region with a single portal, and each team member has a portal within their base at an arbitrary rotation. When entering the vault, it would only make sense to come out of the portal facing north (as it is built into the southern wall, instead of center in the vault), but if a team member has their portal entrance where they face south, it can be a bit frustrating to use.

My thought would be to have a setting on the portal you can click through that controls the orientation for when someone arrives to it.
Normal - current behavior and default
Flipped - still allow 2-direction behavior like normal but flip the direction, so if they enter facing north, they exit a "flipped" portal facing south (might be confusing as a destination only setting unless all portals within a network use this option, but could find some use)
North, East, South, West - always face given direction (and maintain "offset"... that is, if you enter a portal at 20 degrees north of west and exit a "forced north" portal, you would be 20 degrees east of north). Potentially dynamically disable the directions that would face you into the portal frame. Alternatively, assign a forward direction to the portal when constructed and use "forward" and "backward" instead of cardinal directions.

Thanks for taking the time to consider this suggestion. We have just started dipping our toes into using portals so please let me know if I missed this already existing or a similar discussion. I'm sure there is probably a more elegant solution to cover all types of portal cases, but this would be a nice and hopefully simple solution to more elegant wall style portals.

**Comment by oddlama** [comment]
I fully agree, and I'm sorry for taking so long to respond.

Instead of flipping the orientation, I would suggest that I implement a toggle button "normal" vs. "fixed", where fixed orientation
will always cause players to exit the portal facing the right direction (i.e. the side with the inital console, yes you can have multiple consoles). This means flipping the direction only if the player enters from the wrong side.

Would that solve your problem?

**Comment by CosmicCaterpillar** [comment]
Yes that sounds perfect, thanks!
