### ISSUE TITLE
Suggestion: Pl3xmap Support

### ISSUE THREAD

**Issue by knniDE** [oddlama/vane#59]
Support for displaying the markers of all plugins (Portals, Regions, Beds...) on Pl3xmap. So like with Dynmap.
(Pl3xmap: [Plexmap Github](https://github.com/pl3xgaming/Pl3xMap))

**Comment by oddlama** [comment]
Thanks for the suggestion, Pl3xmap looks like a nice project. I will have a look at whats possible with it.
