### ISSUE TITLE
Suggestion: WorldGuard support (more flags)

### ISSUE THREAD

**Issue by Yoshiro09** [oddlama/vane#61]
Heyo!
In my Server I need to block the Home Scroll in a specific region, but there isn't any flag to do it.
Can you, please, add 1 or more flags to prevent players from using vane items in a region?

**Comment by oddlama** [comment]
Technical information:

This can already be solved by a bridge plugin at this moment, in case I decide it isn't worth being integrated into vane directly. There are custom events for portal scrolls and some other vane related actions (portals, regions, ...).

**Comment by oddlama** [comment]
For the moment, we won't implement specific world-guard support. A simple bridge plugin can handle this if needed.
