### ISSUE TITLE
Config system change in 1.6.2 causes Nullpointerexception

### ISSUE THREAD

**Issue by clumar** [oddlama/vane#72]
Just updated a server to minecraft paper 1.18.1 and encountered this bug:
In 1.6.2 when the config system tries to create a new yaml file, it tries to call the 'compatible config file', this however always is null, as it was given null from the version-checker. Maybe this was a temporary placeholder which made it to the pushed release. 
I ended up using the 1.6.1 release for now, which worked as long as I deleted the old config files.

**Comment by oddlama** [comment]
Oh thanks for spotting this. It is actually intended to be passed as null, which means the config generator should use the default values. Will push a fix in 5 minutes.

**Comment by oddlama** [comment]
Release is finished
