### ISSUE TITLE
How to solve the problem of players refusing to accept the resource pack resulting in repeated kicks out？

### ISSUE THREAD

**Issue by moda-haijiao** [oddlama/vane#73]
I have a player on my server who clicked reject when asked if he would accept the resource pack, so how do I get the server to ask again？

**Comment by CosmicCaterpillar** [comment]
Have the player delete the server entry in their multiplayer server list and readd. Should prompt again.

**Comment by oddlama** [comment]
Exactly. This is unfortunately a behavior implemented fully in the client, and the server cannot detect whether it was permanently rejected or temporarily, so I cannot add this into the message.
