### ISSUE TITLE
Suggestion: make the level of Speed effect (when walking on grass paths) configurable

### ISSUE THREAD

**Issue by deNULL** [oddlama/vane#74]
Currently, if fast walking on grass paths is enabled, it always gives players **Speed II** potion effect, which results in 40% speed increase. I feel like it's too much and would prefer **Speed I** effect (i.e. 20% increase).

As I can see, only the duration of the potion effect is configurable right now. It would be nice to be able to configure the level of potion effect as well.

**Comment by oddlama** [comment]
Nice idea, I'll quickly implement this.
