### ISSUE TITLE
which plugins do i use

### ISSUE THREAD

**Issue by master7720** [oddlama/vane#76]
vane-admin-1.6.5.jar 46.6 KB
vane-admin-1.6.5.jar.asc 228 Bytes
vane-bedtime-1.6.5.jar 18.9 KB
vane-bedtime-1.6.5.jar.asc 228 Bytes
vane-core-1.6.5.jar 3.09 MB
vane-core-1.6.5.jar.asc 228 Bytes
vane-enchantments-1.6.5.jar 81.2 KB
vane-enchantments-1.6.5.jar.asc 228 Bytes
vane-permissions-1.6.5.jar 22.9 KB
vane-permissions-1.6.5.jar.asc 228 Bytes
vane-portals-1.6.5.jar 135 KB
vane-portals-1.6.5.jar.asc 228 Bytes
vane-regions-1.6.5.jar 115 KB
vane-regions-1.6.5.jar.asc 228 Bytes
vane-trifles-1.6.5.jar 102 KB
vane-trifles-1.6.5.jar.asc 228 Bytes
vane-waterfall-1.6.5.jar 110 KB
vane-waterfall-1.6.5.jar.asc

**Comment by oddlama** [comment]
Those that you like. Please just follow the [Installation guide](https://github.com/oddlama/vane/wiki/Installation-Guide).
