### ISSUE TITLE
Interacting with Blocks using File gives AureliumSkills XP

### ISSUE THREAD

**Issue by Stonewall0210** [oddlama/vane#86]
As the title says, when right clicking the File on certain blocks such as stone, gravel, sand, and others you gain skill xp. Right clicking on a block placed by a player also makes the plugin believe the block is naturally generated, and rewards xp for breaking it.

How to recreate:
1. Have a File (I tested with a wooden one)
2. Right click it on a natural block or a block you placed

Expected result:
The file does nothing to these blocks

Actual result:
You get experience from interacting with the block, or if you placed it the plugin regards the block as natural, and gives xp on break or further interaction.

**Comment by oddlama** [comment]
Seems like a bug with AureliumSkills XP. To that plugin, the file will look like a hoe. Not sure why this would give XP, but it shouldn't be related to the custom item.
