### ISSUE TITLE
Suggestion: Consider renaming plugin artifacts.

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#88]
It would be very useful if vane changed the ordering of the plugin name artifacts.

e.g. change from vane-{plugin}-{version} to vane-{version}-plugin

it would make updating easier, so instead of having to select and delete interleaving plugins, you could select the group of old ones. 

see screenshot for details.

![image](https://user-images.githubusercontent.com/141554/147565460-83d986f7-3416-4aea-ab4b-a4857b4dd6a3.png)

**Comment by oddlama** [comment]
Certainly not ideal at the moment. I could rename them before uploading, but `vane-{version}-{name}` also doesn't sound quite right to me.

I could remove the version number from the filenames completely, which would allow easy replacing.. I need to think about this more before making a decision.

**Comment by ryantheleach** [comment]
It's a tiny thing in the end, don't let me sway your opinions / needs un-necessarily. I love having the version numbers there, more then I need the ease-of-use when doing my update workflow.

**Comment by oddlama** [comment]
Guess I'll keep it as-is for now. I still dislike the clutter of having so many files tbh, but i guess the modularity is worth it currently.
