### ISSUE TITLE
Feature request: Currency Customization

### ISSUE THREAD

**Issue by Dumfoozle** [oddlama/vane#9]
My server uses XPConomy with Vault plugin.  Is it possible to have Vane (especially Regions) use the Vault currency?  If not, is it possible to specify experience as the currency in the currency material?

**Comment by oddlama** [comment]
I can certainly look into Vault integration. If it doesn't add a lot of technical debt and complexity i will add it in the next release.

**Comment by oddlama** [comment]
I have just implemented and released vault support for regions in v1.1.3.
