### ISSUE TITLE
Vane strips lore already existing on items on anvil combine / rename.

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#94]
With Vane enchants enabled:

![image](https://user-images.githubusercontent.com/141554/147611290-7779a5df-32e0-4f7a-8103-c64f77cbf82e.png)

With Vane Enchants Disabled: 

![image](https://user-images.githubusercontent.com/141554/147611333-576edfc8-d65e-4599-a8a4-e7b286882f0b.png)

Root cause: https://github.com/oddlama/vane/blob/main/vane-enchantments/src/main/java/org/oddlama/vane/enchantments/Enchantments.java#L151

Vane currently clears all lore, every time it updates, what it should be doing, is instead using the existing lore, and only removing lore that it's added previously.

We need some way of marking this lore, the easy way would be to use the translatable components, since they are (presumably) namespaced under vane, we can see them pretty easy.

However this directly clashes with the ability to server-side translate the chat components.

So instead I propose we insert some form of invisible marker, so we can see what lore belongs to vane-enchant, remove all that match, and then update as normal, appending the vane enchants to the list again.

That would mutate the item stacks on every enchanting operation, but it would be a LOT easier then scanning and updating individual enchants + levels.

**Comment by oddlama** [comment]
[memory log from discord discussion]:

Best would be to tag the lines added by vane with a hidden text component, to later update them if necessary but never to delete existing content.

**Comment by oddlama** [comment]
Another thing: Existing books can then no longer be used to craft stuff because of NBT mismatch. Maybe it's time to address this NBT matching issue somehow :/

**Comment by ryantheleach** [comment]
> Another thing: Existing books can then no longer be used to craft stuff because of NBT mismatch. Maybe it's time to address this NBT matching issue somehow :/

I talked to the Recipe Manager dev, and short of using Recipe Manager 2 as a dependency, the path is using Material Choices for the recipes, then validating it afterwards, either in the various recipe result events, or inventory events.

I havn't tested it, but he suspects that they still render the example item correctly.

**Comment by oddlama** [comment]
I'm 99% certain they wont render correctly in the preview on the client. But I guess it's the only way to move forward for us (at least for now)

**Comment by oddlama** [comment]
I just had a new idea to mostly prevent breaking backwards compatibility. If a lore entry is already just a translatable component referencing `vane*:something`, it can always be considered part of vane, no need for a prefix to keep track of it. And that should be the case for 95% of the installs. I'll use your nice prefixing logic when client side translations are disabled, but add those simple translatable components to the list of vane-owned components.

It might cause duplicated texts on those other 5%, but we cannot realistically do anything about that. After all, vane is supposed to be used with client side translations. And if some other plugin stringifies the lore, it's not our problem. It isn't anything we can prevent and therefore I will not create any weird hacks to support it.

**Comment by oddlama** [comment]
[50% done]: Crafting will still be an issue going forward. I can see two paths going forward:

A) We introduce a lightweight item watcher that converts items when they are encountered in some events (maybe item pickup/move/...). Can be done cleanly, and has the added benefit that we can use it for more things later, for example if we want to make breaking changes to custom items.

B) Make the crafting recipes more general (i.e. Material only) and reject invalid materials in an event. This will cause items to be wrongly rendered in recipes on the client recipe book though.

Realistically I think we need to go for A.

**Comment by oddlama** [comment]
The converter that will be introduced next breaking release can also take care of updating items for these situations.

**Comment by ryantheleach** [comment]
> B) Make the crafting recipes more general (i.e. Material only) and reject invalid materials in an event. This will cause items to be wrongly rendered in recipes on the client recipe book though.

I wonder if it's possible to do the opposite, make the items NBT specific, and use the events to make them more general.

They wouldn't shift click nicely from the recipe books though.

An alternative I thought of as I was writing this, is if that fails, register them twice? 

Gives a recipe that 'shows up right' and a different one that 'works right' but looks wrong.

Neither situation would be good, but I wonder if that's a better compromise.

VanillaTweaks / datapacks tend to use a [green recipe book thing ](https://minecraft.fandom.com/wiki/Knowledge_Book)as a placeholder, and detect that being given to the player, we don't need to do that luckily, but it's also an option potentially as some players would be used to seeing these placeholders.

**Comment by oddlama** [comment]
Sounds like you'll always be in some kind of workaround situation. It would just be so good if mojang added support for this natively :/
