### ISSUE TITLE
[partially fixed] Why have you forsaken me, cave-air :(

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#95]
portals can't be built in strongholds because there's `cAvE-aiR`. Should be added to valid blocks in config. Same for void air.

Workaround: Fill the area with blocks and destroy them to get normal air.

**Comment by ryantheleach** [comment]
I've tried to tackle this, but beyond hacking it in, it gets out of hand fast in terms of refactoring.

E.g. you change the portal blocks to a material map, then you see all the 12345 blocks for boundaries, and realize that if you are going to the trouble for changing portal blocks to a material set, then maybe those should be a material set too, then that fundamentally changes how styles are stored.

Which then changes how those blocks are serialized, which affects backwards compatibility, and finally how the user ends up inputting styles...

compared to just special casing air, and leaving the configs alone XD.

I think the full change is worthy, but I'm not sure how to tackle styles.

**Comment by ryantheleach** [comment]
I havn't yet looked at block #tags but maybe they would be more appropriate (for everything except styles anyway, they are basically pre-built material sets)

**Comment by oddlama** [comment]
vane's configs have a version field for this purpose, which is specified in the main file of the respective module. If you want to introduce a breaking change to a config that's no problem. Just increment the version number, replace the `@Config...` field with something else and all users will be forced to review changes on the next update.

I'm not entirely sure how you want to apply block tags to styles, as styles definitely need a specific block to which the portal's blocks are changed to.

If I'm not mistaken, specifying which blocks get classified as area, boundary, etc. should just be config related and not related to how users create styles. The config change although will definitely be tough. (New annotation class necessary, because java annotations are nicely designed so that you can't make them generic :( )

**Comment by ryantheleach** [comment]
I think I may have struggled to communicate where my head had gone. It's possible, but harder for someone new to your codebase was all.

**Comment by oddlama** [comment]
Alright just let me know when it's ready
