### ISSUE TITLE
target lock should not work if the selected portal isnt public

### ISSUE THREAD

**Issue by oddlama** [oddlama/vane#99]
also add the public status for each portal to the selection menu

**Comment by ryantheleach** [comment]
>also add the public status for each portal to the selection menu
 
 I had a quick go at this, but I'm going to have to have the translation system explained to me.

**Comment by oddlama** [comment]
Sure :D I should really document some of the internals..

**Comment by ryantheleach** [comment]
I started work on adding the visibility markers, but I'm not sure what I did wrong: https://github.com/RTLBukkit/vane/commit/dec1f2cc5bebddcfbe719c4509b502abfcd2f1ac
